### ISSUE TITLE
identifying clade-specific genes

### ISSUE THREAD

**Issue by Perugolate** [wdingx/pan-genome-visualization#2]
Is there a way to show clade-specific genes? e.g. after zooming into a particular clade?

**Comment by wdingx** [comment]
Thanks for the feedback. I just added this feature in the following example http://pangenome.tuebingen.mpg.de/P_marinus_meta_clade 
Now, clicking a clade also selects clade-specific genes in the gene cluster table. The selection can be cleared using the "clear clade filter" button.

**Comment by Perugolate** [comment]
Great! I'm looking at my own data on a local server. How can I implement it?

**Comment by wdingx** [comment]
I pushed the changes. Please use "git pull" to fetch the updates and restart the local server.
